### ISSUE TITLE
Unable to update with bundled releases

### ISSUE THREAD

**Issue by aaronmck** [chaibio/chaipcr#4]
We're currently unable to update our real time with the release images (upgrade.img.tar) that we  download. The error message reads "An error occured while uploading software image. Please try again." We've even tried resetting the machine to factory defaults and this doesn't seem to help.  Any suggestions?

**Comment by aaronmck** [comment]
Worked on the second factory reset, third upload. I'm still a bit unclear about the underlying issue.

**Comment by jperfetto** [comment]
Hi Aaron,

I think this issue occurs when upgrading from older software, like pre-1.0.4. Since you have gotten the upgrade to work now, I believe you won't see this issue again when doing future upgrades.

**Comment by aaronmck** [comment]
Hi Josh, 

We saw the same issue on the machine in 1.0.6.X, before we did the initial factory reset.  When it did succeed (in the factory default version), we still saw the error message, but the machine reset at some point later and came back up in 1.0.7.6.  Not a big issue, but worth noting if someone else hits it.

**Comment by jperfetto** [comment]
It's understandable that this issue occurred after the factory reset because then your software will be quite old. It shouldn't have occurred on 1.0.6 though. It may have been some other issue that your factory image reset fixed. If it happens again email us at support@chaibio.com and if we can get teamviewer access to your device we may be able to debug further.
